version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lanterndev
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgdevpassword
    volumes:
      - ./db/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
