version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lanterndev
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgdevpassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
