// Describes the source of the data that an expression variable may draw from
export enum ExpressionVariableType {
  Custom, // Non-standard types provided by the user, generated by a loop, etc
  Actor,
  Content,
  Ruleset,
  Sheet,
}
